### PR TITLE
Feature/show selected emoji

### PR DESCRIPTION
**Pull request by mateki0**
closes https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/102

### CODE REVIEW

**Comment by oferRounds** [comment]
wow nice!!! Thank you so much for this!

**Review by jakex7 — COMMENTED** [review]
Could you move an example to a separate screen (not Basic) in exampleApp and provide code snippet in docs example? I'm not quite sure how it works 🙈

**Review by jakex7 — APPROVED** [review]

**Comment by oferRounds** [comment]
Hi! Any chance this can be merged?

**Comment by oferRounds** [comment]
@jakex7 @mateki0 any thoughts on this one? :)

**Review by jakex7 — APPROVED** [review]

**Pull request merged**
